server_port: 8080

redis:
  url: "redis://localhost:6379"
  pool_max_idle: 3
  pool_max_active: 10

prefixes:
  - uri: "/cars"
    redis_prefix: "cars."
    cache_enabled: true
    cache_refresh_duration: 1s
    cache_ttl: 5s
